#!/usr/bin/env python3
"""Generate project-scoped MCP overrides without copying global credentials."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def servers(workspace: Path, python: Path) -> dict:
    workspace = workspace.resolve(strict=True)
    github = workspace.parent
    semcod = github / "semcod"
    grammar = github / "autogrammar"
    common = {"command": str(python.absolute()), "cwd": str(workspace)}
    return {
        "algitex-code2llm": {
            **common,
            "args": [str(semcod / "algitex/docker/code2llm/code2llm_mcp_server.py")],
            "env": {"ALGITEX_MCP_PROJECT_ROOT": str(workspace), "TRANSPORT": "stdio"},
        },
        "code2logic": {
            **common,
            "command": str(semcod / "code2logic/.venv/bin/python"),
            "args": ["-m", "code2logic.mcp_server"],
            "env": {"CODE2LOGIC_MCP_PROJECT_ROOT": str(workspace)},
        },
        "nlp2cmd": {
            **common,
            "args": ["-m", "nlp2cmd.mcp.server"],
            "env": {"PYTHONPATH": str(grammar / "nlp2cmd/src")},
        },
        "nlp2dsl": {
            **common,
            "args": ["-m", "nlp2dsl_mcp.server"],
            "env": {
                "PYTHONPATH": str(grammar / "nlp2dsl/packages/nlp2dsl-mcp/src"),
                "NLP2DSL_BACKEND_URL": "http://localhost:8010",
                "NLP2DSL_NLP_SERVICE_URL": "http://localhost:8012",
                "NLP2DSL_WORKER_URL": "http://localhost:8004",
            },
        },
        "redup": {
            **common,
            "command": str(semcod / "redup/.venv/bin/redup-mcp"),
            "args": [],
            "env": {"REDUP_ROOT": str(workspace)},
        },
    }


def render(config: dict) -> str:
    lines = ["# Generated by maskservice/.github/mcp/workspace_profile.py; reload the MCP client."]
    for name, server in config.items():
        table = f"mcp_servers.{json.dumps(name)}"
        lines.append(f"\n[{table}]")
        for key in ("command", "args", "cwd"):
            lines.append(f"{key} = {json.dumps(server[key], ensure_ascii=False)}")
        lines.append(f"[{table}.env]")
        lines.extend(f"{key} = {json.dumps(value, ensure_ascii=False)}"
                     for key, value in server["env"].items())
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("workspace", type=Path)
    parser.add_argument("--python", type=Path, default=Path(sys.executable))
    parser.add_argument("--install", action="store_true", help="Create .codex/config.toml; never overwrite it")
    args = parser.parse_args()
    content = render(servers(args.workspace, args.python))
    if args.install:
        target = args.workspace / ".codex/config.toml"
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("x", encoding="utf-8") as stream:
            stream.write(content)
        print(target)
    else:
        print(content, end="")


if __name__ == "__main__":
    main()
